/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cliente.Cliente;
import cliente.Notificable;
import cliente.NotificablePPT;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author carlo
 */
public class Home extends javax.swing.JDialog implements NotificablePPT {

    private String action;
    private Cliente cliente;
    private String nombreOponente;
    private int identificadorOponente;
    private int identificadorCliente;
    private int identificadorSala;

    /**
     * Creates new form Home
     */
    public Home(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        piedra2.setEnabled(false);
        papel2.setEnabled(false);
        tijeras2.setEnabled(false);

        this.action = "";
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
        this.cliente.ejecutarSocketPPT(this);
        jLabelName.setText(this.cliente.getNombre());
    }

    public String getNombreOponente() {
        return nombreOponente;
    }

    public void setNombreOponente(String nombreOponente) {
        this.nombreOponente = nombreOponente;
        jLabelName2.setText(nombreOponente);
    }

    public int getIdentificadorOponente() {
        return identificadorOponente;
    }

    public void setIdentificadorOponente(int identificadorOponente) {
        this.identificadorOponente = identificadorOponente;
    }

    public int getIdentificadorCliente() {
        return identificadorCliente;
    }

    public void setIdentificadorCliente(int identificadorCliente) {
        this.identificadorCliente = identificadorCliente;
    }

    public int getIdentificadorSala() {
        return identificadorSala;
    }

    public void setIdentificadorSala(int identificadorSala) {
        this.identificadorSala = identificadorSala;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelName2 = new javax.swing.JLabel();
        piedra2 = new javax.swing.JButton();
        papel2 = new javax.swing.JButton();
        tijeras1 = new javax.swing.JButton();
        piedra1 = new javax.swing.JButton();
        papel1 = new javax.swing.JButton();
        tijeras2 = new javax.swing.JButton();
        textGanador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabelName.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Usuario:");

        jLabelName2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelName2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName2.setText("Usuario:");

        piedra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/piedra.png"))); // NOI18N
        piedra2.setBorderPainted(false);
        piedra2.setContentAreaFilled(false);

        papel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papel.png"))); // NOI18N
        papel2.setBorderPainted(false);
        papel2.setContentAreaFilled(false);

        tijeras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tijeras.png"))); // NOI18N
        tijeras1.setBorderPainted(false);
        tijeras1.setContentAreaFilled(false);
        tijeras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tijeras1ActionPerformed(evt);
            }
        });

        piedra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/piedra.png"))); // NOI18N
        piedra1.setBorderPainted(false);
        piedra1.setContentAreaFilled(false);
        piedra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piedra1ActionPerformed(evt);
            }
        });

        papel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papel.png"))); // NOI18N
        papel1.setBorderPainted(false);
        papel1.setContentAreaFilled(false);
        papel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papel1ActionPerformed(evt);
            }
        });

        tijeras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tijeras.png"))); // NOI18N
        tijeras2.setBorderPainted(false);
        tijeras2.setContentAreaFilled(false);

        textGanador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(piedra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(papel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(papel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tijeras1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(tijeras2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(piedra1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addGap(459, 459, 459))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(textGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(459, 459, 459))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(818, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(papel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piedra2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tijeras2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tijeras1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(papel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(piedra1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(512, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1316, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void papel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papel1ActionPerformed
        if (!this.action.equals("")) {
            return;
        }
        this.action = "PAPEL";

        try {
            this.cliente.jugarPPT(this.identificadorCliente, this.identificadorSala, this.action);
        } catch (IOException ex) {
            System.out.println(">>ERROR ENVIANDO MENSAJE");
        } catch (JSONException ex) {
            System.out.println(">>ERROR CREANDO JSON CON LA INFORMACION DEL CLIENTE");
        }

        piedra1.setEnabled(false);
        tijeras1.setEnabled(false);
    }//GEN-LAST:event_papel1ActionPerformed

    private void piedra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piedra1ActionPerformed
        if (!this.action.equals("")) {
            return;
        }
        this.action = "PIEDRA";

        try {
            this.cliente.jugarPPT(this.identificadorCliente, this.identificadorSala, this.action);
        } catch (IOException ex) {
            System.out.println(">>ERROR ENVIANDO MENSAJE");
        } catch (JSONException ex) {
            System.out.println(">>ERROR CREANDO JSON CON LA INFORMACION DEL CLIENTE");
        }

        papel1.setEnabled(false);
        tijeras1.setEnabled(false);
    }//GEN-LAST:event_piedra1ActionPerformed

    private void tijeras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tijeras1ActionPerformed
        if (!this.action.equals("")) {
            return;
        }
        this.action = "TIJERAS";

        try {
            this.cliente.jugarPPT(this.identificadorCliente, this.identificadorSala, this.action);
        } catch (IOException ex) {
            System.out.println(">>ERROR ENVIANDO MENSAJE");
        } catch (JSONException ex) {
            System.out.println(">>ERROR CREANDO JSON CON LA INFORMACION DEL CLIENTE");
        }

        piedra1.setEnabled(false);
        papel1.setEnabled(false);
    }//GEN-LAST:event_tijeras1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton papel1;
    private javax.swing.JButton papel2;
    private javax.swing.JButton piedra1;
    private javax.swing.JButton piedra2;
    private javax.swing.JLabel textGanador;
    private javax.swing.JButton tijeras1;
    private javax.swing.JButton tijeras2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ganadorPPT(String mensaje, int idNotificable) {
        try {
            JSONObject obj = new JSONObject(mensaje);

            if (obj.getInt("ganador") == 0) {
                textGanador.setText("ES UN EMPATE");
            }else if(obj.getInt("ganador") == identificadorCliente){
                textGanador.setText("EL GANADOR ES: " + cliente.getNombre());
            }else{
                textGanador.setText("EL GANADOR ES: " + nombreOponente);
            }

            if (obj.getInt("identificador1") == identificadorCliente) {
                if (obj.getString("jugada2").equals("PIEDRA")) {
                    piedra2.setEnabled(true);
                } else if (obj.getString("jugada2").equals("PAPEL")) {
                    papel2.setEnabled(true);
                } else if (obj.getString("jugada2").equals("TIJERAS")) {
                    tijeras2.setEnabled(true);
                }
            } else {
                if (obj.getString("jugada1").equals("PIEDRA")) {
                    piedra2.setEnabled(true);
                } else if (obj.getString("jugada1").equals("PAPEL")) {
                    papel2.setEnabled(true);
                } else if (obj.getString("jugada1").equals("TIJERAS")) {
                    tijeras2.setEnabled(true);
                }
            }
            
            cliente.terminarJuegoPPT();
        } catch (JSONException ex) {
            System.out.println(">>Error obteniendo la informacion");
        }
    }
}
